library(data.table)


#-------------------------------------------------------------------------------------
#                         Most important functions for use
#-------------------------------------------------------------------------------------


#' Retrieve a subset of an expression file filtered by TCGA sample IDs
#' NOTE: If you do not know which values to use for primary_disease and sample_type_id, use process_expression_file(expr_file, sample_annot_file)
#'
#' @param expr_data Expression data in form of a data frame.
#' @param sample_annotation TCGA annotation of samples as data frame.
#' @param primary_disease Name of the cancertype you are interested in.
#' @param sample_type_id A number generated by TCGA as ID for sample types.
#' @return A subset of the expression data with samples matching desired cancer type and sample type as data frame.
process_expression_file <- function(expr_data, sample_annotation, primary_disease = NULL, sample_type_id = NULL){
  sample_list <- retrieve_TCGA_sample_list(sample_annotation, primary_disease = primary_disease, sample_type_id = sample_type_id)
  expr_data_subset <- transpose_and_filter_expression_data_for_samples(expr_data, sample_list)
  return(expr_data_subset)
}



#-------------------------------------------------------------------------------------
#                   Function for TCGA sample annotation file
#-------------------------------------------------------------------------------------


#' Retrieve a list of TCGA samples filtered for primary disease type and sample type.
#' NOTE: If you don not know which values to use for primary_disease and sample_type_id, use retrieve_TCGA_sample_list(sample_annotation)
#'
#' @param sample_annotation TCGA annotation of samples as data frame.
#' @param primary_disease Name of the cancertype you are interested in.
#' @param sample_type_id A number generated by TCGA as ID for sample types.
#' @return A list of TCGA sample IDs for chosen primary disease type and sample type.
retrieve_TCGA_sample_list <- function(sample_annotation, primary_disease = NULL, sample_type_id = NULL){
  sample_type_id <- as.character(as.numeric(sample_type_id))
  
  # Get lists of valid disease types and sample type IDs
  disease_types <- sort(unique(sample_annotation$X_primary_disease))
  sample_types <- unique(subset(sample_annotation, select = c("sample_type_id", "sample_type")))
  sample_types <- sample_types[order(sample_types$sample_type_id),]
  row.names(sample_types) <- NULL

  # Validate input values for primary_disease and sample_type_id
  valid_disease_type <- TRUE
  valid_sample_type <- TRUE
  if(is.null(primary_disease) || missing(primary_disease) || !primary_disease %in% disease_types)
    valid_disease_type <- FALSE
  if(is.null(sample_type_id) || missing(sample_type_id) || !sample_type_id %in% sample_types$sample_type_id)
    valid_sample_type <- FALSE

  # Filter tcga sample annotations for primary_disease and sample_type_id
  sample_list <- NULL
  if(valid_disease_type == FALSE && valid_sample_type == FALSE) {
    cat("\nLIST OF TCGA PRIMARY DISEASE IDENTIFIERS\n")
    cat("----------------------------------------\n\n")
    print(disease_types)
    cat("\n")
    cat("\nLIST OF SAMPLE TYPES WITH INDICES\n")
    cat("---------------------------------\n\n")
    print(sample_types)
    cat("\n")
    quit
  } else if(!valid_disease_type) {
    sample_list <- sample_annotation[sample_annotation$sample_type_id == sample_type_id,]
  } else if(!valid_sample_type) {
    sample_list <- sample_annotation[sample_annotation$X_primary_disease == primary_disease,]
  } else {
    sample_list <- sample_annotation[sample_annotation$X_primary_disease == primary_disease & sample_annotation$sample_type_id == sample_type_id,]
  }

  return(as.vector(sample_list$sample))
}



#-------------------------------------------------------------------------------------
#                         Subset and format expression data
#-------------------------------------------------------------------------------------


transpose_and_filter_expression_data_for_samples <- function(expr_data, sample_list){

  # Get expression data into the right shape
  if(!startsWith(rownames(expr_data)[1], "TCGA"))
    expr_data <- as.data.frame(t(expr_data))
  rownames(expr_data) <- gsub("\\.", "-", rownames(expr_data))
  colnames(expr_data) <- lapply(strsplit(colnames(expr_data), "\\."), '[', 1)

  # Filter expression dataset for sample IDs in sample_list
  expr_data_filtered <- subset(expr_data, row.names(expr_data) %in% sample_list)
  
  # Spot sample IDs missing in the current expression dataset and 
  # build matrix with values of 0 for the missing sample IDs
  missing_sampleids <- sample_list[!(sample_list %in% row.names(expr_data))]
  missing_expr_data <- as.data.frame(matrix(0,
                                            length(missing_sampleids),
                                            length(colnames(expr_data_filtered))))
  row.names(missing_expr_data) <- missing_sampleids
  colnames(missing_expr_data) <- colnames(expr_data_filtered)
  
  # Append matrix with missing sample IDs to the expression dataset
  extended_expr_data <- rbind(expr_data_filtered, missing_expr_data)
  return(extended_expr_data)
}




#-------------------------------------------------------------------------------------
#                         Basic read and write functions
#-------------------------------------------------------------------------------------


readExpressionFile <- function(expr_file){
  expr_data <- data.frame(fread(as.character(expr_file), sep="\t", header = T), row.names = 1)
  colnames(expr_data) <- gsub("\\.", "-", colnames(expr_data))
  return(expr_data)
}


printExpressionFile <- function(expr_data, out_file){
  write.table(expr_data, file = as.character(out_file), sep = "\t", quote = F, row.names = T, col.names = NA)
}




#-------------------------------------------------------------------------------------
#                                     EXAMPLE RUN
#-------------------------------------------------------------------------------------

mir_expr_file <- "/nfs/home/students/evelyn/bachelor/data/TCGA_expression_data/pancanMiRs_EBadjOnProtocolPlatformWithoutRepsWithUnCorrectMiRs_08_04_16.xena"
  #"D:\\Bioinformatics\\Bachelordata\\TCGA_expression_data\\pancanMiRs_EBadjOnProtocolPlatformWithoutRepsWithUnCorrectMiRs_08_04_16_breastcancer.xena"
tpm_expr_file <- "/nfs/home/students/evelyn/bachelor/data/TCGA_expression_data/tcga_Kallisto_tpm"
sample_annot_file <- "/nfs/home/students/evelyn/bachelor/data/TCGA_expression_data/cancertype_filter/TCGA_phenotype_denseDataOnlyDownload.tsv"
  #"D:\\Bioinformatics\\Bachelordata\\TCGA_expression_data\\cancertype_filter\\TCGA_phenotype_denseDataOnlyDownload.tsv"
#out_file <- "/nfs/home/students/evelyn/bachelor/data/TCGA_expression_data/tcga_mirna_breastinvasivecarcinoma_primarytumor_test.tsv"
expr_data <- readExpressionFile(tpm_expr_file)
sample_annotation <- read.csv(sample_annot_file, header = T, sep = "\t")
expr_subset <- process_expression_file(expr_data, sample_annotation, "breast invasive carcinoma", "01")
#process_and_print_expression_file(expr_file, sample_annot_file, "breast invasive carcinoma", "01", out_file)

#mirna_expr <- readExpressionFile("/nfs/home/students/evelyn/bachelor/data/TCGA_expression_data/tcga_mirna_breastinvasivecarcinoma_solidtissuenormal.tsv")
#tpm_expr <- readExpressionFile("/nfs/home/students/evelyn/bachelor/data/TCGA_expression_data/tcga_tpm_breastinvasivecarcinoma_solidtissuenormal.tsv")
#extended_data <- crossextend_expression_data(mirna_expr, tpm_expr)
#extended_mirna_expr <- as.data.frame(extended_data[1])
#extended_tpm_expr <- as.data.frame(extended_data[2])
